# Generated by Django 5.0.6 on 2024-05-09 17:04

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registrationmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('fatherName', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('adharCardNumber', models.CharField(max_length=200, null=True)),
                ('penCardNumber', models.CharField(max_length=200, null=True)),
                ('phoneNumber', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('zipCode', models.CharField(max_length=200, null=True)),
                ('nomineName', models.CharField(max_length=200, null=True)),
                ('nominegender', models.CharField(max_length=200, null=True)),
                ('nominedob', models.DateField(default=django.utils.timezone.now)),
                ('nominePhoneNumber', models.CharField(max_length=200, null=True)),
                ('bankAccountNumber', models.CharField(max_length=200, null=True)),
                ('bankAccountHolder', models.CharField(max_length=200, null=True)),
                ('bankName', models.CharField(max_length=200, null=True)),
                ('ifscCode', models.CharField(max_length=200, null=True)),
                ('branchName', models.CharField(max_length=200, null=True)),
                ('dateTimeCreated', models.DateField(default=datetime.date.today)),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
