# Generated by Django 5.0.6 on 2024-05-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login_registration', '0002_registrationmodel_sponserid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationmodel',
            old_name='id',
            new_name='memberSponserId',
        ),
    ]
