# Generated by Django 5.0.6 on 2024-05-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login_registration', '0005_alter_registrationmodel_membersponserid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='memberSponserId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
